import discord 
import mysql.connector
import random 

client = discord.Client()
#mysql local server details.
mydb = mysql.connector.connect(
    host = "localhost" ,
    user = "root",
    passwd = "Sallysarr357",
    database = "userlevels",
    #auth_plugin = ""
    
)

TOKEN = ('NzcxMzA0NTIzMDc0ODk1ODcy.X5qLUA.8pfLAaPMrk1OMlEHIQgcoVa9x8A')
#this generates a random xp for the users.
def generatexp():
    return random.randint(0, 900)

#shows that the bot is logged in 
@client.event 
async def on_ready():
    print("bot is ready to go")
    print(mydb)

#the message function which shows how the message works.
@client.event 
async def on_message(message):
    if message.author.bot:
        return 
    
    if message.content.lower() == '.help':
        pass 
    if message.content.lower() == '.coinflip':
        pass
    else:
        #this genrates xp for the user. 
        xp = generatexp()
        print(message.author.name + " will receive " + str(xp) + "xp")
        cursor = mydb.cursor()
        #here we select the new user_level column to be more specific.
        cursor.execute("SELECT users_xp, user_level FROM users WHERE client_id = " + str(message.author.id))
        #this code doesn't work for some reason. its supposed to fectchall 
        result = cursor.fecthall()
        print(result)
        if(len(result) == 0):   
            print("user is not in db... add them.")
            #user_level is default set to 1.
            cursor.execute("INSERT INTO users values(" + str(message.author.id) + "," + str(xp) + ", 1)")
            mydb.commit()
            print("inserted...")
        else:
            #the new xp is the amount of points given to someone that uses the server.
            newXP = result[0][0] + xp
            #new xp is generated by adding the result to the old xp.
            currentLevel = result[0][1]
            print("new xp " + str(newXp))
            print("current level" + str(currentLevel))


            #this are the xp points given based on the user level.
            if newXP < 300:
                currentLevel = 1
                #if its less than 300 then the user is on level 1.
            elif newXp > 300 and newXp < 550:
                currentLevel = 2
                #if its bewteen 300 and 550 then the user is on level 2.
            elif newXp > 550 and newXp < 800:
                # if its between 550 and 800 then the user is on level 3.
                currentLevel = 3

            cursor.execute("UPDATE users SET user_xp = " + str(newXP) + ", user_level = " + str(currentLevel) + "WHERE client_id = " + str(message.author.id))
            mydb.commit()
            print("updated...")

            #embedded mesages
            #allows users to send embedded messages.
            embed = discord.Embed()
            embed.set_author(name = 'Test Account')
            embed.description = message.author.name + str(xp) + " xp..."
            
            await message.channel.send(embed=embed)


#this allows the code to be connected to the bot.
client.run('NzcxMzA0NTIzMDc0ODk1ODcy.X5qLUA.8pfLAaPMrk1OMlEHIQgcoVa9x8A')

